name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_firebase_auth:
    path: ../

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

dependency_overrides:
  stacked_firebase_auth:
    path: ../

flutter:
  uses-material-design: true

