name: stacked_firebase_auth
description: A service class that provides Firebase Authentication Functionality on a single api
version: 2.21.0
homepage: https://stacked.filledstacks.com/
repository: https://github.com/Stacked-Org/firebase_auth.git
issue_tracker: https://github.com/Stacked-Org/framework/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_auth_platform_interface: ^8.1.5

  # Firebase Authentications
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.5

  # logging
  logger: ^2.6.2

  crypto: ^3.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
