name: stacked_firebase_auth
description: A service class that provides Firebase Authentication Functionality on a single api
version: 2.20.1
homepage: https://stacked.filledstacks.com/
repository: https://github.com/pmmucsd/stacked_firebase_auth.git
issue_tracker: https://github.com/Stacked-Org/framework/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_auth_platform_interface: ^7.0.0

  # Firebase Authentications
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^6.2.0

  # logging
  logger: ^2.3.0

  crypto: ^3.0.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
