name: stacked_firebase_auth
description: A service class that provides Firebase Authentication Functionality on a single api
version: 2.19.3
homepage: https://stacked.filledstacks.com/
repository: https://github.com/Stacked-Org/firebase_auth.git
issue_tracker: https://github.com/Stacked-Org/framework/issues

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_auth_platform_interface: ^6.11.0

  # Firebase Authentications
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.3.0

  # logging
  logger: ^1.4.0

  crypto: ^3.0.3

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter: